In [65]:
#Outcome: Visualize the data from Toronto Awarded Contracts

import numpy as np
import pandas as pd

import re

import matplotlib.pyplot as plt
import seaborn as sns

In [66]:
#Retrive data

df = pd.read_csv("./Awarded Contracts.csv")
df.head(2)

,_id,unique_id,Document Number,RFx (Solicitation) Type,High Level Category,Successful Supplier,Awarded Amount,Award Date,Division,Buyer Name,Buyer Email,Buyer Phone Number,Solicitation Document Description
0,1,84b49458-9376-4812-9a7b-79dda5ce4cf2_1,Doc3512316731,RFSQ,Construction Services,Trans Canada Construction,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
1,2,84b49458-9376-4812-9a7b-79dda5ce4cf2_2,Doc3512316731,RFSQ,Construction Services,Anacond Contracting,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   _id                                842 non-null    int64
 1   unique_id                          842 non-null    object
 2   Document Number                    842 non-null    object
 3   RFx (Solicitation) Type            842 non-null    object
 4   High Level Category                842 non-null    object
 5   Successful Supplier                839 non-null    object
 6   Awarded Amount                     842 non-null    object
 7   Award Date                         841 non-null    object
 8   Division                           821 non-null    object
 9   Buyer Name                         842 non-null    object
 10  Buyer Email                        842 non-null    object
 11  Buyer Phone Number                 842 non-null    object
 12  Solicitation Document Description  775 non-null    object
dtypes: int64(1), object(12)
memory usage: 85.6+ KB

In [68]:
df.dropna()

,_id,unique_id,Document Number,RFx (Solicitation) Type,High Level Category,Successful Supplier,Awarded Amount,Award Date,Division,Buyer Name,Buyer Email,Buyer Phone Number,Solicitation Document Description
0,1,84b49458-9376-4812-9a7b-79dda5ce4cf2_1,Doc3512316731,RFSQ,Construction Services,Trans Canada Construction,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
1,2,84b49458-9376-4812-9a7b-79dda5ce4cf2_2,Doc3512316731,RFSQ,Construction Services,Anacond Contracting,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
2,3,84b49458-9376-4812-9a7b-79dda5ce4cf2_3,Doc3512316731,RFSQ,Construction Services,Area Construction,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
3,4,84b49458-9376-4812-9a7b-79dda5ce4cf2_4,Doc3512316731,RFSQ,Construction Services,BDA Inc,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
4,5,84b49458-9376-4812-9a7b-79dda5ce4cf2_5,Doc3512316731,RFSQ,Construction Services,Dole Contracting,0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
837,838,7412168a-7ea0-494b-ad44-6867c7478b93_1,Doc4587869729,RFQ,Goods and Services,Five Star Enterprises of Canada Ltd.,"$76,869.90",2025-02-21,Purchasing & Materials Management,Jeffrey San Miguel,Jeffrey.SanMiguel@toronto.ca,4163974825,The non-exclusive supply and delivery of safet...
838,839,8d7ad091-1619-4943-9832-56e5c5e8daf4_1,Doc4726186752,RFP,Professional Services,Parsons Inc.,"12,157,623.60",2025-01-15,Engineering & Construction Services,Penny Petridis,Penny.Petridis@toronto.ca,4163948127,Request for Proposals for Engineering Services...
839,840,10b9f552-c387-4ac1-9e26-1dec620d94e5_1,Doc4574804004,RFT,Construction Services,KUDLAK-BAIRD 1982 LIMITED,"394,838.00",2024-09-13,Corporate Real Estate Management,Karen Peralta,Karen.Peralta@toronto.ca,4163385606,This Request for Tenders is an invitation by t...
840,841,baf3ecfb-01aa-452c-9a1c-09f7ca0cc25b_1,Doc4207675073,RFP,Goods and Services,INTERNATIONAL NAME PLATE SUPPLIES LIMITED,"156,490.75",2024-06-09,Corporate Real Estate Management,Karen Peralta,Karen.Peralta@toronto.ca,4163385606,Request for Quotations for the Union Station S...
841,842,35571c38-4050-4c4b-ae05-7ab91fd9c14d_1,Doc4571351491,RFP,Professional Services,The West Egg Group Security Services,"4,775,849.68",2024-09-30,Corporate Real Estate Management,Karen Peralta,Karen.Peralta@toronto.ca,4163385606,This RFP is an invitation by the City of Toron...

In [69]:

price_col = "Awarded Amount"
if price_col in df.columns:
    df[price_col] = (
        df[price_col]
        .astype(str)
        .replace(r'[\$,]', '', regex=True)
        .replace(r'[^0-9.\-]+', '', regex=True)
        .replace(r'\s+', '', regex=True)
        .replace('', '0', regex=False)
        .astype(float)
    )

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842 entries, 0 to 841
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   _id                                842 non-null    int64
 1   unique_id                          842 non-null    object
 2   Document Number                    842 non-null    object
 3   RFx (Solicitation) Type            842 non-null    object
 4   High Level Category                842 non-null    object
 5   Successful Supplier                839 non-null    object
 6   Awarded Amount                     842 non-null    float64
 7   Award Date                         841 non-null    object
 8   Division                           821 non-null    object
 9   Buyer Name                         842 non-null    object
 10  Buyer Email                        842 non-null    object
 11  Buyer Phone Number                 842 non-null    object
 12  Solicitation Document Description  775 non-null    object
dtypes: float64(1), int64(1), object(11)
memory usage: 85.6+ KB

In [71]:
# Data Assumptions and Limitation

# Records that have a dollar amount of 0 in the Contract Value or Award Value fields may be the result of solicitations 
# (ie: Requests for Supplier Qualifications) being used to obtain a pre-qualified list of suppliers to use for future solicitations. 
# No dollar amounts are immediately associated with these types of solicitations

# The objective of this is to vsualize the most accurate information about the bidding process.

In [72]:
# Categorical Variables
#   1.  "RFx (Solicitation) Type"
#   2.  "High Level Category"
#   3.  "Successful Supplier"
#   4.  "Award Date"
#   5.  "Division"

# Numeric Variables
#   1.  "_id"
#   2.  "Awarded Amount"

In [ ]:
# Number Contracts by Month & Year
# High Level Category vs Price
# Price by Month & Year
#

In [73]:
categorial_variables = ["RFx (Solicitation) Type",
                     "High Level Category",
                     "Successful Supplier",
                     "Award Date",
                     "Division"
                     ]

numeric_variables = ["_id",
                     "Awarded Amount"
                     ]

In [74]:
categorical=pd.array
for i in categorial_variables:
    categorical=df[i].unique
    
categorical

<bound method Series.unique of 0         Corporate Real Estate Management
1         Corporate Real Estate Management
2         Corporate Real Estate Management
3         Corporate Real Estate Management
4         Corporate Real Estate Management
                      ...
837      Purchasing & Materials Management
838    Engineering & Construction Services
839       Corporate Real Estate Management
840       Corporate Real Estate Management
841       Corporate Real Estate Management
Name: Division, Length: 842, dtype: object>

In [75]:
df_zero_dollar = df[df["Awarded Amount"] == 0.0]

df_zero_dollar.head(2)

,_id,unique_id,Document Number,RFx (Solicitation) Type,High Level Category,Successful Supplier,Awarded Amount,Award Date,Division,Buyer Name,Buyer Email,Buyer Phone Number,Solicitation Document Description
0,1,84b49458-9376-4812-9a7b-79dda5ce4cf2_1,Doc3512316731,RFSQ,Construction Services,Trans Canada Construction,0.0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."
1,2,84b49458-9376-4812-9a7b-79dda5ce4cf2_2,Doc3512316731,RFSQ,Construction Services,Anacond Contracting,0.0,2023-05-08,Corporate Real Estate Management,Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,"General Contractors for New Construction, Reno..."

In [76]:
df_price = df[df["Awarded Amount"] != 0.0]

df_price.head(2)

,_id,unique_id,Document Number,RFx (Solicitation) Type,High Level Category,Successful Supplier,Awarded Amount,Award Date,Division,Buyer Name,Buyer Email,Buyer Phone Number,Solicitation Document Description
14,15,b347eaf5-9744-44b3-a5d2-a2f9a8a09395_1,Doc3718447124,RFQ,Goods and Services,Asplundh Canada ULC,5952260.16,2023-07-11,"Parks, Forestry & Recreation",Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,This Request for Proposals (RFP) is an invitat...
15,16,b347eaf5-9744-44b3-a5d2-a2f9a8a09395_2,Doc3718447124,RFQ,Goods and Services,Diamond Tree Care & Consulting Inc.,4941090.00,2023-07-11,"Parks, Forestry & Recreation",Ryan Phelan,Ryan.Phelan@toronto.ca,4163974814,This Request for Proposals (RFP) is an invitat...

In [ ]:
categorical_var_unique ={}
for variable in categorial_variables:
    categorical_var_unique[variable] = df_price[variable].unique()

In [ ]:
for variable in categorial_variables:
    print(f"Category: {variable} | {categorical_var_unique[variable]}")

Category: RFx (Solicitation) Type | [array(['RFQ', 'RFP', 'RFT', 'RFSQ', 'OTP', 'NRFP'], dtype=object)]
Category: High Level Category | [array(['Goods and Services', 'Professional Services',
       'Construction Services', 'Offer to Purchase', 'Goods & Services'],
      dtype=object)]
Category: Successful Supplier | [array(['Asplundh Canada ULC', 'Diamond Tree Care & Consulting Inc.',
       'Weller Tree Service Ltd', 'Davey Tree Expert Co', 'ePlanSoft',
       'Enterprise Rent A Car Canada',
       '1246175 Ontario Limited o/a Active Mechanical Services',
       'STRUCT-CON CONSTRUCTION LTD', 'AG REAT CONSTRUCTION CO LTD',
       'PHOENIX RESTORATION INC.', 'JOE PACE & SONS CONTRACTING INC',
       'ROSSCLAIR CONTRACTORS INC', 'ANACOND CONTRACTING INC',
       'ACTIVE MECHANICAL SERVICES', 'STATE GROUP INC, THE',
       'MJ DIXON CONSTRUCTION', 'Shutter Professionals Inc.',
       'Season Group', 'Executive Mat Service Ltd.',
       'Canadian Linen and Uniform Service',
       'SQM Janitorial Services Inc.', 'Flint Packaging Products',
       'Blended Perspectives Inc.',
       'North Fringe Industrial Technologies',
       'Cooper Equipment Rentals Limited o/a Cooper Pump and Power',
       'Compugen Inc', 'The Armstrong Monitoring Corporation',
       'DLS TECHNOLOGY CORPORATION', 'MID-ONTARIO TRUCK CENTRE',
       '1106499 ONTARIO LIMITED KIFF AUTO', 'WILCOX DOOR SERVICE INC',
       'CUBEX LIMITED', 'TOROMONT MATERIAL HANDLING',
       'Kooy Brothers Lawn Equipment LTD', 'NEXGEN MUNICIPAL INC',
       'JOE JOHNSON EQUIPMENT', 'GK CHEMICAL SPECIALTIES CO',
       'RUSH TRUCK CENTER OF CANADA', 'Mid - Ontario Truck Center',
       'NX Auto Body',
       'Consolidated Automotive Resources Group Ltd. o/a Mastertech Auto Body & Service Centre',
       'Calisi Motors Ltd. o/a Sherway Collision',
       'O-Two Medical Technologies Inc.', 'ADVANCE SOLUTIONS CORPORATION',
       'BIO NUCLEAR DIAGNOSTICS INC', 'Dican',
       'HUMBERVIEW CHEVROLET BUICK GMC', 'GUILLEVIN INTERNATIONAL CO',
       'ANRONN ELECTRIC MOTOR REPAIR', 'Bell Canada o/a Bell, BCE Inc.',
       'Metro Freightliner Hamilton Inc. o/a Metro Truck Group',
       'Mid-Ontario Diesel Ltd. o/a Mid-Ontario Truck Centre',
       'Enex Engraving', '2281610 ONTARIO INC,DOWNTOWN FORD',
       'Systems Plus', 'Supply Line o/a Supplyline Inc.',
       'SOUTHERN SANITATION O/A WASTECO',
       'Calisi Motors Limited o/a Sherway Collision',
       'Eurasia (Canada) Cars and Truck Centre',
       'CARDINAL HEALTH CANADA INC', 'SOLID CADDGROUP INC',
       'BENCH CRAFT LEATHER INC', 'Amaco Construction Equipment Inc.',
       'DOWNTOWN AUTO GROUP', 'Zamboni Company Limited',
       'TALOS TECHNOLOGIES INC.', 'ONTARIO SEWER SERVICES INC',
       'ONX ENTERPRISE SOLUTIONS LTD', 'FLYING COLOURS INTERNATIONAL',
       'AMACO CONSTRUCTION EQUIPMENT INC.', 'Mid-Ontario Truck Centre',
       'DOUGLAS POWERTECH ENTERPRISES INC.',
       'ALLIED MEDICAL INSTRUMENTS INC', 'Stinson Equipment Ltd.',
       'Nexgen Municipal Inc.', 'MCL - MISTER CHEMICAL LTD',
       'LEICA GEOSYSTEMS LTD', 'Rush Truck Centres of Canada',
       'Via Trailers Bolton', 'PILLAR TAPES LTD',
       'Aon Solutions Canada Inc.', 'SPERIDIAN TECHNOLOGIES CANADA INC',
       'READ JONES CHRISTOFFERSEN LTD', 'iPSS Inc.',
       'QUASAR CONSULTING GROUP INC', 'CHERIE NG ARCHITECT INC',
       'JOHNSON CONTROLS LTD', 'VIPOND INC', 'MET-SCAN CANADA LTD',
       'PALADIN TECHNOLOGIES INC', 'ARUP CANADA INCORPORATED', 'ASP INC',
       'WEST EGG GROUP SECURITY SERVIC', 'GARDA',
       'KEYDATA ASSOCIATES INC', 'MARKLAND PROPERTY MANAGEMENT INC.',
       'C.E.S. ENGINEERING LTD.', 'TAURUS CONTRACTING, A DIV OF TCL',
       'TRIBRO GROUP LTD', 'Grascan Construction Ltd',
       'CIMCO Refrigeration, div. of Toromont Industries Ltd.',
       'Joe Pace & Sons Contracting Inc.', 'FERDOM CONSTRUCTION',
       '373044 ONT LTD/TRANS CANADA CONSTRUCTION',
       'MOPAL CONSTRUCTION LTD', 'Hank Deenen Landscaping Limited',
       'Pine Valley Corporation', 'Pine Valley Corp',
       '671860 Ontario Inc. o/a Somerville Construction',
       'SOUTH CENTRAL INC', 'Joe Pace & Sons Contracting Inc',
       'Midome Construction Services Ltd.', 'Pegah Construction Ltd.',
       'Semple Gooder Roofing Corporation',
       'LIMEN GROUP CONST. (2019) LTD', 'FRANK PELLEGRINO GEN CONT LTD',
       'COSAR GC PM', 'CANADIAN SAFETY EQUIPMENT LTD',
       'DE VROOMEN BULB CANADA INC', 'DUTCHMASTER NURSERY',
       'Formost Data Products Inc.', 'Urban Tactical Brantford Ltd.',
       'Office Central Inc.', 'Entomogen Incorporated',
       '1913574 Ontario Inc. oa Royal Oak Tree Services Inc.',
       'Guillevin International Co.', 'Cardinal Health Canada Inc',
       'Sysco', 'Joerns Healthcare Canada Inc.',
       'ARIVA, DIVISION OF DOMTAR INC', 'SPICERS CANADA ULC',
       'Kooy Brothers Lawn Equipment Ltd.', 'K-Dental Inc.',
       'STREET GRAFFITI SOLUTIONS', 'Firechek Protection Services Inc.',
       'Dignity Transportation Inc.', 'Power King Exhaust Cleaning',
       'Masters Golf Carts Inc', 'ONTARIO LINE CLEARING & TREE EXPERT',
       'WM WELLER TREE SERVICE LTD', nan, 'Forest Ridge Landscaping Inc.',
       'DAFCO FILTRATION GROUP CORPORATION', 'KR COMMUNICATIONS LTD',
       'ALPINE BUILDING MAINTENANCE INC',
       'TRH SERVICES (BRANDON BIOMED INC)',
       'CLINTAR LANDSCAPE MANAGEMENT (Downtown Groundskeeping Services)',
       'AQUA TECH SOLUTIONS INC', 'Salivan Landscape Inc.',
       'Lomco Limited', '5028901 Ontario Inc. o/a Royal Oak Services',
       'SUSTAINABLE ROOTS ECOLOGICAL RESTORATION INC',
       'BRINKMAN & ASSOCIATES REFORESTATION LTD', 'SALIVAN LANDSCAPE LTD',
       'NORSECO INC.', 'GILES RESTORATION SERVICES INC',
       'URBAN FOREST ASSOCIATES INC', 'RESTORATION ARTISTS',
       ' SYSCO TORONTO, A DIVISION OF SYSCO CANADA INC. ',
       'SYSCO TORONTO, A DIVISION OF SYSCO CANADA INC.',
       'RESOLVE SUPPORT SERVICES',
       'LIFTSAFE ENGINEERING AND SERVICE GROUP INC',
       'BERRN CONSULTING LTD',
       'THEODORE ANTHONY ROQUE (DREAM CATCHER FIREWORKS)',
       'DAYCO DISTRIBUTING LTD', 'Canadian Hearing Services',
       'CBV COLLECTION SERVICES LTD', 'GATESTONE & CO INC',
       'PARTNERS IN CREDIT INC', 'GENERAL CREDIT SERVICES INC',
       'COLLECTCENTS INC.', 'NATIONAL CREDIT RECOVERY INC', 'ARO INC',
       'INTERNATIONAL CREDIT EXPERTS INC', 'MJR CAPITAL SERVICES INC',
       'CS&P ARCHITECTS INC', 'KONGATS ARCHITECTS',
       'Stantec Consulting Ltd', 'VERITY INTERNATIONAL LTD',
       'IBI Group Professional Services (Canada) Inc. SLA Landscape Design and Planning Inc. (Canada)',
       'KOPPERT BIOLOGICAL SYSTEMS LTD', 'DTAH',
       'CANADIAN OBSERVATORY ON HOMELESSNE',
       'The George Hull Centre for Children and  Families',
       'Plant Architect Inc.', 'CULTURE CHECK INC', 'KPMG LLP',
       'Insight Advantage Inc.',
       'Thinc Design (Tocher Heyblom Design Inc.)', 'Culture Check Inc.',
       'Production Service Industries', 'Light and Dark Inc',
       'Solotech Inc', 'Achieva', 'SLBC Inc.',
       'Peter T. Mitches & Associates Limited',
       'PETER T MITCHES & ASSOCIATES LIMITE', 'KPMG',
       'Strategic Measures',
       'BRINKMAN AND ASSOCIATES REFORESTATION LIMITED',
       'SUSTAINABLE ROOTS ECOLOGICAL RESTORATION INC.', 'MEP DESIGNS INC',
       'PINE VALLEY CORPORATION', 'Distinct Concrete Cutting Inc.',
       'Anacond Contracting Inc.', 'UTILITY FORCE CONSTRUCTION INC',
       '614128 ONTARIO LTD, O/A TRISAN CONSTRUCTION',
       'Green Infrastructure Partners Inc.',
       'Martinway Contracting Limited', 'D CRUPI & SONS LIMITED',
       'Hawkins Contracting Services Limited', 'Ritestart Limited',
       'Capital Sewer Services Inc.', 'Waste Management of Canada Corp.',
       'WSN CONSTRUCTION INC',
       '614128 Ontario Ltd. o/a Trisan Construction', 'ES Fox Ltd',
       'PTR Paving inc.', 'Aqua Tech Solutions Inc.',
       'Canada Construction Limited', 'Stinson Equipment Limited',
       'Aerzen Canada', 'CSL Group ltd.', 'CANADA CONSTRUCTION LIMITED',
       'MARTINWAY CONTRACTING LTD', 'Bennett Mechanical Installations',
       'D MARTINO CONSTRUCTION LTD', 'Dynex Construction Inc.',
       'Grascan Construction Ltd.', 'Clearway Construction Inc',
       '373044 Ontario Limited O/A Trans Canada Construction',
       'INSITUFORM TECHNOLOGIES LTD', 'LISHEY METAL FABRICATION LTD',
       '2489960 ONTARIO INC.', 'Midome Construction services Ltd',
       'Viola Management Inc.', 'BRIDGECON CONSTRUCTION LTD',
       'Fer-Pal Construction Ltd.', 'PTR Paving Inc',
       'Viola Management Inc', 'PTR Paving Inc.', 'Maple-Crete Inc.',
       'BROOK RESTORATION LTD', 'WSP CANADA INC', 'MAPLE-CRETE INC',
       'Vaughan Paving Ltd.', 'RAFAT GENERAL CONTRACTOR INC',
       'SANSCON CONSTRUCTION LIMITED', 'Midome Construction Services Ltd',
       'IL Duca contracting Inc.', 'INFRASTRUCTURE COATINGS CORPORATION',
       'GRASCAN CONSTRUCTION LTD / TORBRIDGE CONSTRUCTION LTD',
       'KLEINGBURG CONTRACTING LTD',
       'Superior Boiler Works and Welding Ltd.', '2489960 Ontario Inc',
       'BRENNAN PAVING & CONSTRUCTION',
       'FOUR SEASONS SITE DEVELOPMENT LTD', 'Aqua Tech Solutions Inc',
       'LCD Mechanical Inc.', 'Green Infrastructure Partners Inc',
       'VAUGHAN PAVING LTD', '1460973 Ontario Ltd. O/A C.P. Systems',
       'PNJ ENGINEERING INC', 'Drainstar Contracting Ltd.',
       'Greenspace Construction Inc', 'UPPER CANADA ROAD SERVICES INC',
       'PEGAH CONSTRUCTION LTD', 'VIOLA MANAGEMENT INC',
       'Midome Construction Services Inc', 'DURON ONTARIO LTD',
       'Direct Underground Inc.', 'PTR Paving Ltd', 'D CRUPI AND SONS',
       'Maple Crete Inc', 'Clearwater Structures Inc',
       'KAPP INFRASTRUCTURE INC', '2220742 ONTARIO LTD',
       '2489960 Ontario Inc. o/a Kore Infrastructure Group',
       'ALLIANCE VERDI CIVIL INC', 'Continental Carbon Group Inc.',
       'D.Crupi & Sons Limited', 'BELOR CONSTRUCTION LTD',
       'M.E. Andrews and Associates Limited', 'DYNA ENGINEERING LTD',
       '2489960 ONTARIO INC', 'Sanscon Construction Ltd',
       'SCHOUTEN EXCAVATING', 'Alberici Constructors Ltd.',
       'Clearway Construction Inc.', 'MULTISEAL',
       'MIDOME CONSTRUCTION SERVICES LTD', 'Guild Electric Limited',
       'BEVCON CONSTRUCTION & PAVING LTD', 'Laundry on Wheels',
       'Five Star Enterprise', 'Auto Guyz Tire', 'Portugal Auto garage',
       'BDS Fleet Services', 'North Keele Auto', 'Hogan Chevrolet Buick',
       'Dependable Emergency Vehicles', 'Safetek Emergency Vehicles Ltd.',
       'SAFEDESIGN APPAREL LTD', 'Metro Compactor Service Inc.',
       'Control Gap Inc.', 'Black and McDonald Limited',
       'Thermo Fisher Scientific', 'Britespan Building Systems',
       'Nachurs Alpine Solutions Inc.', 'Superior Air Systems',
       'INTERNATIONAL CYBERNETICS CANADA INC', 'Mississauga Steel Mart',
       'TURKSTRA MODULAR BUILDERS INC',
       'Woodbine Pavement Markings Limited', 'Stinson Equipment Ltd',
       'Graphix Source canada', 'Supco Construction Ltd.',
       'Valley Integration Inc.', 'Markham Metals Ltd.',
       'Combined Metal Industries Inc.', 'CDMV Inc.', 'XYLEM CANADA LP',
       'FLOCHEM LTD', '416 Vactor Inc.', 'UBA INC',
       'Paris Site Furnishings and Outdoor Fitness',
       'Gallops Waste Management', '2503396 Ontario Inc',
       'SAFE ROADS ENGINEERING INC', 'DSR Systems Inc.',
       'STANTEC CONSULTING LTD', 'The Control Institute Inc.',
       'Howden Roots LLC', 'RHI Canada Inc.', 'The Planning Partnership',
       'LMDG Building Code Consultants', 'WSP Canada Inc.', 'GHD Limited',
       'IBI GROUP PROFESSIONAL SERVICES Canada Inc',
       'Access Planning Ltd.', 'RV Anderson Associated Ltd.',
       'ERA Architects Inc', 'Three Sisters Consulting',
       'Aecom Canada Ltd.', 'EXP Services Inc.', 'MOON-MATZ LTD',
       'ATA ARCHITECTS INC', 'ARCADIS PROFESSIONAL SERVICES',
       'GM BLUEPLAN ENGINEERING LIMITED',
       'GM Blueplan Engineering Limited', 'Spectrum Traffic Data Inc.',
       'GHD Contractors Limited', 'Urban Systems Ltd',
       'Davroc Testing laboratories Inc.', 'SNC Lavalin Inc.',
       'Wood E & I (WSP E&I Canada Limited)',
       'GANNETT FLEMING CANADA ULC', 'AECOM Canada Ltd.',
       'Parcel Economics Inc.',
       'ARCADIS PROFESSIONAL SERVICES (CANADA) INC',
       'FIRST BASE SOLUTIONS INC', 'Supco Construction Limited',
       'QUEENSWAY EXCAVATING & LANDSCAPING LTD.', 'APGN Inc.',
       'Dye & Durham Corporation', 'DYE & DURHAM CORPORATION',
       'RV ANDERSON ASSOCIATES LTD', 'Testmark Laboratories Ltd',
       'MOON-MATZ LTD.', 'Sutherland-Schultz Ltd.', 'Carraway Inc.',
       'AAI CORP.', '2192222 Ontario Inc. dba Sunshine Grounds Care',
       'GHD LIMITED', 'CIMA Canada Inc.', 'CIMA CANADA INC',
       'MORRISON HERSHFIELD LTD', 'Morrison Hershfield',
       'Chemtrade Chemicals Canada Ltd.', 'Morneau Shepell Ltd.',
       'Capital Sewer Services Inc', 'Belor Construction Ltd.',
       'PMC WATER SYSTEMS SERVICES INC', 'SUTHERLAND SCHULTZ LTD',
       'Triumph Roofing & Sheet Metal Inc.', 'HARRISON MUIR INC',
       'MNA ENGINEERING LTD', 'BEARCOM CANADA CORPORATION',
       'AQUICON CONSTRUCTION CO LTD', 'CONCEPT FIATLUX INC.',
       'WEST 8 URBAN DESIGN AND LANDSCAPE ARCHITECTURE BV (WEST 8 PR)',
       'AECOM CANADA LTD', 'SALIVAN LANDSCAPE INC', 'EXP SERVICES INC',
       'INTERNATIONAL NAME PLATE SUPPLIES LIMITED',
       'ONTARIO WATER WERX INC.', 'ARALIA INTERIOR PLANTSCAPING  INC',
       'Integral Group', 'A.S.P. Incorporated', 'ATLAS CONSTRUCTORS INC',
       'TRIUMPH ALUMINUM & SHEET METAL INC',
       'FOUR SEASONS SIT DEVELOPMENT LTD.',
       '7850891 CANADA INC/EGNATIA PAVING', 'TEAMWORKS MANUFACTURING INC',
       'BEAR COMMUNICATIONS INC', 'MULTIVIEW LOCATES INC',
       'Infrastructure Coatings Corporation ', 'DELOITTE LLP',
       'SONCIN CONSTRUCTION CORPORATION',
       'Arcadis Professional Services (Canada) Inc.',
       'MOPAL CONSTRUCTION LTD.', 'LOMCO LIMITED',
       'LANS CONSTRUCTION & CONTRACTING LTD', 'INDEX CONSTRUCTION INC',
       'BUTLER CONTRACTING GROUP INC', 'LINCOLN PAVING & CONTRACTING LTD',
       'Goodbye Graffiti Toronto West Levi Cleaning Services Inc',
       'Walker Environmental Group Inc.', 'Insituform Technologies Ltd.',
       'Metro Freightliner Hamilton Inc',
       'MEDLINE CANADA CORP O/A MEDICAL MAR', 'RICOH CANADA INC',
       'ALTUS GROUP LIMITED', 'Kroll Consulting Canada Co.',
       'SUNCORP VALUATIONS', 'LOGIXX SECURITY INC',
       'WALKER ENVIRONMENTAL GROUP INC', 'AVRON FOODS LTD',
       'Levi Cleaning Services Inc O/A Goodbye Graffiti Toronto West',
       'GRASCAN CONSTRUCTION LTD', 'UTILITY FORCE INC',
       'OJCR CONSTRUCTION LTD', 'ALLIANCE VERDI CIVIL INC.', 'PTR PAVING',
       'Signority Inc.', 'Black and McDonald LTD',
       'GARDA CANADA SECURITY CORPORATION', 'WEBTACTICS INC',
       'IAN MARTIN LIMITED', 'DRAKE INTERNATIONAL INC', 'HR ASSOCIATES',
       'BEVERTEC CST INC', 'QUANTUM MANAGEMENT SERVICES LTD',
       'O2 PLANNING + DESIGN', 'CRCE CONSTRUCTION LTD',
       'Utility Force Construction Inc.', 'PTR PAVING INC',
       'Stericycle ULC', 'Black & McDonald Ltd.',
       'Infrastructure Coatings (Ontario) Corporation ',
       'D. Crupi & Sons Limited', 'Optiv Canada Inc.', 'SSG',
       'BLACK & MCDONALD LIMITED', 'FER-PAL CONSTRUCTION LTD',
       'MARBRIDGE CONSTRUCTION LTD.', 'Alliance Verdi Civil Inc',
       'A&F Di Carlo Construction Inc.',
       'Bevcon Construction & Paving Ltd.', 'CSPN',
       'Garage Supply Contracting Inc.', 'ROMA FENCE LTD',
       'SCHINDLER ELEVATOR CORPORATION',
       'Ridge Road Training & Consulting Inc.',
       'Monteith Brown Planning Consultants Ltd.',
       'PATTERNED CONCRETE ONTARIO INC.',
       'Environics Research Group Ltd.', 'Torbear Contracting Inc',
       'GRAHAM BROS. CONSTRUCTION LIMITED',
       'Gallops Waste Management Inc.', 'CH2M Hill Canada Limited',
       'PRODUCTION SERVICE INDUSTRIES', 'MISTER CHEMICAL LTD',
       'Morrison Hershfield Limited',
       'PPL AQUATIC FITNESS AND SPA GROUP INC.', 'RITESTART LIMITED',
       'PREMIER TRUCK GROUP OF MISSISSAUGA', 'Power Station Inc.',
       'NORTHERN GENERATOR COMPANY', 'SOFTCHOICE LP', 'CLASSIC DISPLAYS',
       'MONARCH MECHANICAL LTD', 'COLIO ESTATE WINES INC',
       'Silv-Econ LTD', 'RIDGE ROAD TRAINING & CONSULTING, INC',
       'MONTEITH BROWN PLANNING CONSULTANTS LTD.',
       'BENNETT MECHANICAL INSTALLATIONS', 'DAMEN SHIPBUILDING 5 B.V.',
       'TORBEAR CONTRACTING INC', 'ROBERT B SOMERVILLE CO. LIMITED',
       'CAPITAL SEWER SERVICES INC',
       '1460973 ONTARIO LIMITED O/A C.P. SYSTEMS',
       'A & F DI CARLO CONSTRUCTION INC.',
       'GRAHAM BROS CONSTRUCTION LTD.', 'GAZZOLA PAVING LIMITED',
       '11913930 CANADA INC.', 'GALLOPS WASTE MANAGEMENT',
       'Gartner Canada', 'PARSONS INC', 'ENVIRONICS RESEARCH GROUP',
       'JACOBS CONSULTANCY CANADA INC', 'Ideaspace Consulting Inc.',
       'INLAND LIFERAFTS & MARINE LTD', 'STERICYCLE, ULC',
       'Erritt Construction Ltd.', 'TAYLOR SMYTH ARCHITECTS',
       'GENERAL DIVING CONTRACTORS INC', 'Ocean Mechanical Inc.',
       'ILLUMIN DRONE SHOW COMPANY INC.', 'GROUPE FIATLUX-AMPLEMAN',
       'TORONTO VETERINARY EMERGENCY HOSPITAL & REFERRAL SERVICES',
       'VETERINARY EMERGENCY HOSPITAL OF WEST TORONTO',
       'Civica Infrastructure', 'Flowmetrix Technical Services Inc.',
       'ADS Environmental Technologies, Inc.', 'Vendor: KPMG LLP',
       'Timbel Limited', 'HAWKINS CONTRACTING SERVICES LIMITE',
       'Agilent Technologies Canada Inc.', 'King Ursa Inc.',
       'Hortico Inc.', 'Dutchmaster Nursery ',
       'Neil Vanderkruk Holdings Inc.', 'Uxbridge Nurseries Limited',
       'QUADRA CHEMICALS LTD', 'SNF CANADA LTD.',
       'DAVIS FEED & FARM SUPPLY LTD', 'Parsons Inc',
       'DRAINSTAR CONTRACTING LTD', 'GIP PAVING INC', '373044 ONT LTD',
       'IPE CANADA INC.', 'SLALOM CONSULTING ULC',
       'PRICEWATERHOUSECOOPERS LLP', 'CATALYST CONSULTING GROUP',
       'CARAHSOFT TECHNOLOGY CORP', 'DELOITTE', 'TRIDENT AUTO GLASS INC',
       'afghan auto glass inc', 'hitplay',
       'Innovative Surface Solutions LP', '2324523 ONTARIO INC',
       'INLAND LIFERAFTS AND MARINE', 'GEORGE COUREY INC.',
       'TIMBEL LIMITED', 'CLEARWAY CONSTRUCTION INC',
       'TORONTO VETERINARY EMERGENCY HOSPITAL',
       'Veterinary Emergency Hospital Of West Toronto',
       'AVENSYS SOLUTIONS INC.', 'ADS ENVIRONMENTAL TECHNOLOGIES, INC.',
       'DETECTRONIC LTD.', 'SNF CANADA LTD', 'AGILENT TECHNOLOGIES INC',
       'UNIVAR SOLUTIONS', 'FRONTDESK QUEUE MANAGEMENT SYSTEMS INC',
       'THE CENTENNIAL CENTRE FOR SCIENCE AND TECHNOLOGY',
       'CIVICA INFRASTRUCTURE INC', 'Flowmetrix Technical Services',
       'OCEAN MECHANICAL INC', 'URBAN FOREST INNOVATIONS INC',
       'Canadian Tire Corporation, Limited',
       '373044 Ont Ltd o/a Trans Canada Construction',
       'Sanscon Construction Ltd.', 'Finch Paving (1993) Inc',
       'Veolia Canada', 'AIRFLOW DEFLECTOR', 'People Corporation',
       'TRUSERVE GROUNDSCARE INC OA CLINTAR LANDSCAPE MANAGEMENT',
       'Stitch it Canadas Tailor Inc', 'KING URSA INC.',
       'WA STEPHENSON MECHANICAL', 'URBAN FOREST INNOVATIONS INC.',
       'FINCH PAVING (1993)INC', 'DESIGN SPACE TRAILERS INC.',
       'Canadian Tire Corporation', 'ARUP CANADA INC.',
       'Allied Medical Instruments Inc.',
       'Chem-Aqua, Div. of NCH Canada Inc.', 'SHERIDAN NURSERIES LIMITED',
       'Five Star Enterprises of Canada Ltd.', 'Parsons Inc.',
       'KUDLAK-BAIRD 1982 LIMITED',
       'The West Egg Group Security Services'], dtype=object)]
Category: Award Date | [array(['2023-07-11', '2023-05-04', '2023-10-01', '2023-03-06',
       '2023-06-29', '2023-12-18', '2023-07-24', '2023-12-05',
       '2023-08-02', '2024-04-03', '2024-01-25', '2024-04-05',
       '2024-03-01', '2024-04-12', '2023-01-01', '2023-05-15',

In [81]:
grouped_division_supplier = df_price.groupby(["High Level Category", "Successful Supplier"])["Awarded Amount"].sum()
print(grouped_division_supplier)

High Level Category    Successful Supplier
Construction Services  1246175 Ontario Limited o/a Active Mechanical Services     3414610.10
                       1460973 ONTARIO LIMITED O/A C.P. SYSTEMS                   3286438.00
                       1460973 Ontario Ltd. O/A C.P. Systems                      6315345.00
                       2220742 ONTARIO LTD                                       19540533.95
                       2489960 ONTARIO INC                                       22338667.00
                                                                                    ...
Professional Services  WEST EGG GROUP SECURITY SERVIC                             6895162.08
                       WSP Canada Inc.                                            1594388.66
                       Wood E & I (WSP E&I Canada Limited)                         882314.27
                       ePlanSoft                                                  1580950.00
                       iPSS Inc.                                                   513862.61
Name: Awarded Amount, Length: 600, dtype: float64

In [78]:

for variable in categorial_variables:
    x_variable = df_price[[variable]].values
    y = df_price["Awarded Amount"].values

In [79]:
for variable in categorial_variables:
    x_variable = df_price[[variable]].values
    y = df_price["Awarded Amount"].values
    
print(x_variable)
'''
    # Create a scatter plot for the each categorical value against the awarded price
    plt.figure(figsize=(6, 4))
    plt.scatter(x_variable, y, label='Data', color='blue')
    
    # Add labels and title
    plt.xlabel(variable)
    plt.ylabel('Awarded Amount')
    plt.title(f'{variable} vs Awarded Amount')    

    # Legend
    plt.legend()

    # Show the Plot
    plt.show()
    
'''

[['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ["City Manager's Office"]
 ['Fleet Services']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Employment & Social Services']
 ['Corporate Real Estate Management,Shelter, Support & Housing Administration']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 [nan]
 ['Purchasing & Materials Management']
 ['Facilities Management']
 ['Facilities Management']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Information & Technology']
 ['Fleet Services']
 ['Fleet Services']
 ['Toronto Water']
 ['Corporate Real Estate Management']
 ['Technology Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Corporate Real Estate Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Revenue Services']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Corporate Real Estate Management,Parks, Forestry & Recreation,Solid Waste Management Services']
 ['Technology Services']
 ['Fire Services,Fleet Services,Toronto Paramedic Services']
 ['Fire Services,Fleet Services,Toronto Paramedic Services']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Purchasing & Materials Management']
 ['Corporate Real Estate Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['City Planning,Technology Services']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Office of the Chief Information SecurityÂ\xa0Officer (CISO)']
 ['Corporate Real Estate Management']
 ['Technology Services']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Technology Services']
 ['Engineering & Construction Services']
 ['Technology Services,Toronto Water']
 ['Technology Services,Transportation Services']
 ['Fleet Services']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Technology Services']
 ['Technology Services']
 ['Finance & Treasury Services']
 ['Technology Services']
 ['Corporate Real Estate Management']
 ['Technology Services']
 ['Real Estate Services']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Environment & Climate']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Office of the Chief Information SecurityÂ\xa0Officer (CISO)']
 ['Fleet Services']
 ['Technology Services']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ["Children's Services"]
 ["Children's Services"]
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Economic Development & Culture']
 ['Economic Development & Culture']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Economic Development & Culture']
 ['Shelter, Support & Housing Administration']
 ['Fire Services']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Employment & Social Services']
 ['Toronto Paramedic Services']
 ["Children's Services"]
 ['Toronto Public Health']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ["City Clerk's Office"]
 ["City Clerk's Office"]
 ['Parks, Forestry & Recreation']
 ['Toronto Public Health']
 ['Economic Development & Culture']
 ['Fire Services']
 ['Seniors Services and Long-Term Care']
 ['Purchasing & Materials Management']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Economic Development & Culture']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Seniors Services and Long-Term Care']
 ['Toronto Paramedic Services']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Parks, Forestry & Recreation']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Court Services']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Shelter, Support & Housing Administration']
 [nan]
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Shelter, Support & Housing Administration']
 ["Children's Services"]
 ['Parks, Forestry & Recreation']
 ["Children's Services"]
 ['City Planning']
 ["City Clerk's Office"]
 ['Parks, Forestry & Recreation']
 ["Children's Services"]
 ['Economic Development & Culture']
 ['Economic Development & Culture']
 ['Economic Development & Culture']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Social Development, Finance & Administration']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Parks, Forestry & Recreation']
 ['Transportation Services']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Engineering & Construction Services - Engineering Services']
 ['Engineering & Construction Services - Engineering Services']
 ['Engineering & Construction Services - Engineering Services']
 ['Engineering & Construction Services - Engineering Services']
 [nan]
 ['Solid Waste Management Services']
 ['Engineering & Construction Services - Capital Works Delivery']
 [nan]
 ['Solid Waste Management Services']
 ['Parks, Forestry & Recreation']
 [nan]
 ['Toronto Water']
 [nan]
 ['Parks, Forestry & Recreation']
 [nan]
 ['Toronto Water']
 ['Transportation Services']
 ['Transportation Services']
 ['Parks, Forestry & Recreation']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Solid Waste Management Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Solid Waste Management Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Corporate Real Estate Management']
 ['Engineering & Construction Services']
 ['Solid Waste Management Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Corporate Real Estate Management']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Purchasing & Materials Management']
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 ['Fire Services']
 ['Fire Services']
 ['Fire Services']
 ['Municipal Licensing & Standards']
 ['Solid Waste Management Services']
 ['Information & Technology']
 ['Transportation Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Toronto Water']
 ['Toronto Water']
 ['Transportation Services']
 ['Fire Services']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Solid Waste Management Services']
 ['Transportation Services']
 ['Municipal Licensing & Standards']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Toronto Water']
 ['Toronto Water']
 ['Toronto Water']
 ['Transportation Services']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Parks, Forestry & Recreation']
 ['Engineering & Construction Services']
 ['Transportation Services']
 [nan]
 ['Toronto Water']
 ['Parks, Forestry & Recreation']
 ['City Planning']
 ['Facilities Management']
 ['Toronto Building']
 ['Solid Waste Management Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services - Engineering Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Fire Services']
 ['City Planning']
 ['City Planning']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Toronto Water']
 ['Toronto Water']
 ['Transportation Services']
 ['Toronto Water']
 ['City Planning']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['City Planning']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Technology Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Municipal Licensing & Standards']
 ['Municipal Licensing & Standards']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Municipal Licensing & Standards']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Pension, Payroll & Employee Benefits']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Technology Services']
 ['Corporate Real Estate Management']
 ['Toronto Water']
 ['Parks, Forestry & Recreation']
 ['Solid Waste Management Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Technology Services']
 ['Toronto Water']
 ['Corporate Real Estate Management']
 ['Engineering & Construction Services']
 ['Solid Waste Management Services']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Parks, Forestry & Recreation']
 ['Seniors Services and Long-Term Care']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Environment & Climate']
 ['Corporate Real Estate Management']
 ['Parks, Forestry & Recreation']
 ['Toronto Water']
 ['Toronto Water']
 ['Solid Waste Management Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Purchasing & Materials Management']
 ['Solid Waste Management Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Office of the Chief Information SecurityÂ\xa0Officer (CISO)']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Corporate Real Estate Management,Municipal Licensing & Standards,Parks, Forestry & Recreation,Toronto Water,Transportation Services']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Transportation Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Corporate Real Estate Management']
 ['Fleet Services']
 ['Purchasing & Materials Management']
 ['Purchasing & Materials Management']
 ['Technology Services']
 ['Finance & Treasury Services']
 ['Finance & Treasury Services']
 ['Finance & Treasury Services']
 ['Environment & Climate']
 ['Corporate Real Estate Management']
 ["Children's Services"]
 ["Children's Services"]
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Toronto Water']
 ['Corporate Real Estate Management,Municipal Licensing & Standards,Parks, Forestry & Recreation,Toronto Water,Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Technology Services']
 ['Purchasing & Materials Management']
 ['Solid Waste Management Services']
 ['People & Equity']
 ['People & Equity']
 ['People & Equity']
 ['People & Equity']
 ['People & Equity']
 ['People & Equity']
 ['People & Equity']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['City Planning']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Toronto Paramedic Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Engineering & Construction Services']
 ['Technology Services']
 ['Environment & Climate']
 ['Toronto Water']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Toronto Water']
 ['Transportation Services']
 ['Municipal Licensing & Standards']
 ['Engineering & Construction Services']
 ['Fire Services,Fleet Services,Toronto Paramedic Services']
 ['Parks, Forestry & Recreation']
 ['Corporate Real Estate Management']
 ['Engineering & Construction Services']
 ['Engineering & Construction Services']
 ['Toronto Water']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['Parks, Forestry & Recreation']
 ['City Planning']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Transportation Services']
 ['Parks, Forestry & Recreation']
 ['Solid Waste Management Services']
 ['Toronto Water']
 ['Engineering & Construction Services']
 ['Economic Development & Culture']
 ['Seniors Services and Long-Term Care']
 ['City Planning']
 ['Engineering & Construction Services']
 ['Corporate Real Estate Management']
 ['Corporate Real Estate Management']
 ['Purchasing & Materials Management']
 ['Purchasing & Materials Management']
 ['Fleet Services']
 ['Corporate Real Estate Management,Seniors Services and Long-Term Care,Solid Waste Management Services']

"\n    # Create a scatter plot for the each categorical value against the awarded price\n    plt.figure(figsize=(6, 4))\n    plt.scatter(x_variable, y, label='Data', color='blue')\n    \n    # Add labels and title\n    plt.xlabel(variable)\n    plt.ylabel('Awarded Amount')\n    plt.title(f'{variable} vs Awarded Amount')    \n\n    # Legend\n    plt.legend()\n\n    # Show the Plot\n    plt.show()\n    \n"

In [80]:
'''
fig, (ax1, ax2) = plt.subplots(
    ncols=2,
    nrows=1,
    figsize=(7,3)
)

ax1.scatter(x1,y1)
ax2.bar(x2,y2)
fig.show()
ax2.grid()

'''

'\nfig, (ax1, ax2) = plt.subplots(\n    ncols=2,\n    nrows=1,\n    figsize=(7,3)\n)\n\nax1.scatter(x1,y1)\nax2.bar(x2,y2)\nfig.show()\nax2.grid()\n\n'